<?php
/**
 * Template for block Mage_Adminhtml_Block_Catalog_Product_Helper_Form_Gallery_Content
 */
?>
<?php
$_block = $this;
/* @var $_block Mage_Adminhtml_Block_Catalog_Product_Helper_Form_Gallery_Content */
?>
<script type="text/javascript" src="http://127.0.0.1/2023/magento/js/lib/uploader/flow.min.js"></script>
<script type="text/javascript" src="http://127.0.0.1/2023/magento/js/lib/uploader/fusty-flow.js"></script>
<script type="text/javascript" src="http://127.0.0.1/2023/magento/js/lib/uploader/fusty-flow-factory.js"></script>
<script type="text/javascript" src="http://127.0.0.1/2023/magento/js/mage/adminhtml/uploader/instance.js"></script>
<div id="<?php echo $_block->getHtmlId() ?>" >
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li>
            <?php echo Mage::helper('banner')->__('Image type and information need to be specified for each store view.'); ?>
            </li>
        </ul>
    </li>
</ul>
<form action="<?php echo Mage::getUrl('*/*/saveGrid', array('group_id' => $this->getRequest()->getParam('group_id'))); ?>" method="post">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div style="display:flex;">
        <div style="width: 90%"><h2><b>Manage Banner Grid</b></h2></div>
        <div style="width: 10% "><button type="submit">Save</button>
</div>
    </div>
    <div>
        <table style="border: 1px solid black; width:100%;">
            <tr>
                <th>Banner Id</th>
                <th>Group Key</th>
                <th>Image</th>
                <th>Status</th>
                <th>Position</th>
                <th>Created At</th>
            </tr>
            <?php foreach ($this->getBannerCollection() as $data) : ?>
            <tr>
                <td><?php echo $data->banner_id ?></td>
                <td><?php echo $data->group_id ?></td>
                <td><img src="<?php echo Mage::getBaseUrl('media') . DS . 'Banner' . DS . 'resized'. DS .$data->image ?>"></td>
                <td>
                    <select name="status[<?php echo $data->banner_id ?>]">
                        <?php $selected = ($data->status == 1) ? "selected" : "" ; ?>
                        <option value="1" <?php echo $selected ?>>Active</option>
                        <?php $selected = ($data->status == 2) ? "selected" : "" ; ?>
                        <option value="2" <?php echo $selected ?>>Inctive</option>
                    </select>
                </td>
                <td><input name="position[<?php echo $data->banner_id ?>]" type="text" value="<?php echo $data->position ?>" style='width: 70px;' ></td>
                <td><?php echo $data->created_at ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</form>
<form action="<?php echo Mage::getUrl('*/*/uploadImage', array('group_id' => $this->getRequest()->getParam('group_id'))); ?>" method="post" enctype="multipart/form-data">
<?php echo $this->getBlockHtml('formkey'); ?>
    <input type="file" name="images[]" multiple>
    <button type="submit">Upload</button>
</form>

<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save" name="<?php echo $_block->getElement()->getName() ?>[images]" value="<?php echo $_block->escapeHtml($_block->getImagesJson()) ?>" />
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save_image" name="<?php echo $_block->getElement()->getName() ?>[values]" value="<?php echo $_block->escapeHtml($_block->getImagesValuesJson()) ?>" />
<script type="text/javascript">
//<![CDATA[
var <?php echo $_block->getJsObjectName(); ?> = new Product.Gallery('<?php echo $_block->getHtmlId() ?>', <?php echo $_block->getImageTypesJson() ?>);
//]]>
</script>
