<style type="text/css">
.container{
  display: flex;
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  text-align: center;
  font-family: arial;
}

.price {
  color: grey;
  font-size: 22px;
}

.card button {
  border: none;
  outline: 0;
  padding: 12px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

.card button:hover {
  opacity: 0.7;
}
</style>
<div>
    <div class="container">
    <?php foreach ($this->getBrands() as $brand): ?>
        <div class="homepage-banner card">
            <p><a href="<?php echo $this->getBaseUrl().'media'.DS.'Brand'.DS.'Banner'.DS.$brand->banner; ?>">
              <img src="<?php echo Mage::getBaseUrl('media') . DS. 'Brand' . DS . $brand->image; ?>" alt="<?php echo $brand->name; ?>" style="width:100%"/>
            </a></p>
            <h1><?php echo $brand->name; ?></h1>
            <p><?php echo $brand->description; ?></p>
        </div>
    <?php endforeach; ?>
    </div>
</div>